feign:
  client:
    config:
      default:       #服务名，填写default为所有服务
        connectTimeout: 1000
        readTimeout: 2000
        loggerLevel: basic
  hystrix:
    enabled: true # 打开Hystrix熔断功能
#在application.properties中配置debug=true，该属性置为true的时候，\
#  核心Logger（包含嵌入式容器、hibernate、spring）会输出更多内容，但是你自己应用的日志并不会输出为DEBUG级别。
# 在运行命令后加入--debug标志，如：$ java -jar springTest.jar --debug
debug: true
