
package com.rh.example.ws.client.oms;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "CERPWSService2Service", targetNamespace = "http://data.ws.datahub/", wsdlLocation = "http://ip:port/datahubWeb/TMSSOAP/SY?wsdl")
public class CERPWSService2Service
    extends Service
{

    private final static URL CERPWSSERVICE2SERVICE_WSDL_LOCATION;
    private final static WebServiceException CERPWSSERVICE2SERVICE_EXCEPTION;
    private final static QName CERPWSSERVICE2SERVICE_QNAME = new QName("http://data.ws.datahub/", "CERPWSService2Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ip:port/datahubWeb/TMSSOAP/SY?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CERPWSSERVICE2SERVICE_WSDL_LOCATION = url;
        CERPWSSERVICE2SERVICE_EXCEPTION = e;
    }

    public CERPWSService2Service() {
        super(__getWsdlLocation(), CERPWSSERVICE2SERVICE_QNAME);
    }

    public CERPWSService2Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CERPWSSERVICE2SERVICE_QNAME, features);
    }

    public CERPWSService2Service(URL wsdlLocation) {
        super(wsdlLocation, CERPWSSERVICE2SERVICE_QNAME);
    }

    public CERPWSService2Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CERPWSSERVICE2SERVICE_QNAME, features);
    }

    public CERPWSService2Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CERPWSService2Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IERPWSService2
     */
    @WebEndpoint(name = "CERPWSService2Port")
    public IERPWSService2 getCERPWSService2Port() {
        return super.getPort(new QName("http://data.ws.datahub/", "CERPWSService2Port"), IERPWSService2.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IERPWSService2
     */
    @WebEndpoint(name = "CERPWSService2Port")
    public IERPWSService2 getCERPWSService2Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://data.ws.datahub/", "CERPWSService2Port"), IERPWSService2.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CERPWSSERVICE2SERVICE_EXCEPTION!= null) {
            throw CERPWSSERVICE2SERVICE_EXCEPTION;
        }
        return CERPWSSERVICE2SERVICE_WSDL_LOCATION;
    }

}
