info:
  head: head
  body: body
management:
  endpoints:
    web:
      exposure:
        #加载所有的端点，默认只加载了info、health. 此处慎用，加载了所有端点，不安全
        include: '*'
  endpoint:
    health:
      show-details: always
    #可以关闭指定的端点
    shutdown:
      enabled: false