
package com.rh.example.ws.client.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MobileAddressImpl", targetNamespace = "http://impl.server.ws.example.rh.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MobileAddressImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAddressByMobile", targetNamespace = "http://impl.server.ws.example.rh.com/", className = "com.rh.example.ws.client.stub.GetAddressByMobile")
    @ResponseWrapper(localName = "getAddressByMobileResponse", targetNamespace = "http://impl.server.ws.example.rh.com/", className = "com.rh.example.ws.client.stub.GetAddressByMobileResponse")
    @Action(input = "http://impl.server.ws.example.rh.com/MobileAddressImpl/getAddressByMobileRequest", output = "http://impl.server.ws.example.rh.com/MobileAddressImpl/getAddressByMobileResponse")
    public String getAddressByMobile(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
